#-------------------------------
# General Site Settings

title: Arduino Türk Batu
logo: https://yt3.ggpht.com/ytc/AKedOLSBczkcFOS3S4vqvJbWZwKvArJeb0Wj7UUu5j_mqg=s88-c-k-c0x00ffffff-no-rj 
author: arduinoturkbatu
description: Arduino Türk Batu'nun öz websitesine ziyaret etmeyen kaldı mı?
email: batuakyar07@gmail.com
phone: NAN
address: NAN
copyright: Copyright &copy; 2022-♾️ Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Selam! 👋 <br> Ben  Arduino <br> Türk Batu

social:
- {icon: "ti-instagram", link: "https://instagram.com/arduinoturkbatu"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCwGhWHqg4HuKZ0C9j4vjGxg"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  2011'de Adana'da dünyaya geldim. 2016'da Antalya'ya gittim. 2018'de kendi YouTube kanalımı açtım. Şimdi ise YouTube kanalımda videolar çekiyorum.

blurb-btn-link: '/about'
blurb-btn-name: daha fazla


# About Page

# Work Process Section
work-process:
  - title : "Arduino"
    icon : "https://cdn-icons-png.flaticon.com/512/908/908742.png"
    content : "Arduino, açık kaynaklı olan bir programlama kartıdır."
    
  - title : "HTML5"
    icon : "https://cdn-icons.flaticon.com/png/512/1073/premium/1073666.png?token=exp=1643131601~hmac=8a9dbf984074af68fabe6edb449dd010"
    content : "HTML (Hyper Text Markup Language), web siteleri için temel koddur."
    
  - title : "Scratch"
    icon : "https://cdn-icons-png.flaticon.com/512/919/919846.png"
    content : "Scratch, genelde çocuk odaklı bir websitesidir. Bu websitesi sayesinde oyunlar, hikayeler, animasyonlar yapılır."


#-------------------------------
# Skills Section

skills-title: Başarılarım
skills:
- {name: Web Tasarım, color: '#fdb157', value: '90%'}
- {name: Arduino, color: '#0055ff', value: '90%'}
- {name: Visual Studio, color: '#0099ff', value: '80%'}
- {name: App Invertor, color: '#2bc48a', value: '75%'}


#-------------------------------
# Exprerience Section

experience-title: Zaman Çizelgesi
experience:
- {name: Arduino, icon: 'icon-1.png', date: '2018 - Şimdi', organization: ''}
- {name: App Invertor, icon: 'icon-2.png', date: '2020 - Şimdi', organization: ''}
- {name: HTML5 , icon: 'icon-3.png', date: '2021 - Present', organization: ''}
    


#-------------------------------
# Contact Section

contact-title: İletişim
contact-email: batuakyar07@gmail.com
