#-------------------------------
# General Site Settings

title: Arduino Türk Batu
logo: assets/images/atblong.png 
author: arduinoturkbatu
description: Arduino Türk Batu'nun öz websitesine ziyaret etmeyen kaldı mı?
mail: batuakyar07@gmail.com
phone: NAN
address: NAN
copyright: Copyright &copy; 2022-∞ [Themefisher](https://themefisher.com) tarafından tasarlandı & [Getjekyllthemes](https://getjekyllthemes.com) tarafından kodlandı.

menu:
- {name: HAKKIMDA, link: '/about'}
- {name: MAKALELER, link: '/blog'}
- {name: PROJELER, link: '/projects'}
- {name: İLETİŞİM, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: arduinotrkbatu


#-------------------------------
# Hero Section

hero:
  hero-title: Selam! 👋 <br> Ben  Arduino <br> Türk Batu

social:
- {icon: "ti-instagram", link: "https://instagram.com/arduinoturkbatu"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCwGhWHqg4HuKZ0C9j4vjGxg"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  2011'de Adana'da dünyaya geldim. 2016'da Antalya'ya gittim. 2018'de kendi YouTube kanalımı açtım. Şimdi ise YouTube kanalımda videolar çekiyorum.

blurb-btn-link: '/about'
blurb-btn-name: daha fazla


# About Page

# Work Process Section
work-process:
  - title : "Arduino"
    icon : "assets/images/icons/arduino.png"
    content : "Arduino, açık kaynaklı olan bir programlama kartıdır."
    
  - title : "HTML5"
    icon : "assets/images/icons/html.png"
    content : "HTML (Hyper Text Markup Language), web siteleri için temel koddur."
    
  - title : "Scratch"
    icon : "assets/images/icons/scratch.png"
    content : "Scratch, genelde çocuk odaklı bir websitesidir. Bu websitesi sayesinde oyunlar, hikayeler, animasyonlar yapılır."


#-------------------------------
# Skills Section

skills-title: Başarılarım
skills:
- {name: Web Tasarım, color: '#fdb157', value: '90%'}
- {name: Arduino, color: '#0055ff', value: '90%'}
- {name: Visual Studio, color: '#0099ff', value: '80%'}
- {name: App Invertor, color: '#2bc48a', value: '75%'}

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbNsIGd-kxYxLZHAEGR2pnjG"
    
  - image : "https://i.ytimg.com/vi/X8eryWWqyLE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBw7ur7CVKig-DpnqvlRIEpNDlWAQ"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbM5yU6ZWNGUF4MmHZcxqGGa"
    
  - image : "https://i.ytimg.com/vi/hrLXWeZSZHQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDAoeWe7lEBXNpFva1qVjzDy3JZfQ"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbPsOMm5BoDXW9njO2Jz18yq"
    
  - image : "https://i.ytimg.com/vi/-iVkE5BjZ7o/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDVXdc4RJEQCEUMSflfs4iKR04s1g"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbMGiGPOKnkPKLXAj8bXkTmf"
    
  - image : "https://arduinoturkbatu.github.io/tulyacss/assets/img/logo.png"
    url: "https://arduinoturkbatu.github.io/tulyacss"


# Portfolio Page
portfolio-label:
- {
    title : "ARDUINO",
    type : "arduino"
  }
- {
    title : "WEB",
    type : "web"
  }
- {
    title : "SCRATCH",
    type : "scratch"
  }
- {
    title: "mBlock",
    type: "mblock"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbNsIGd-kxYxLZHAEGR2pnjG"
    portfolio-type:
     - type: "arduino"
  - image : "https://i.ytimg.com/vi/X8eryWWqyLE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBw7ur7CVKig-DpnqvlRIEpNDlWAQ"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbM5yU6ZWNGUF4MmHZcxqGGa"
    portfolio-type:
      - type: "web"
      
  - image : "https://i.ytimg.com/vi/hrLXWeZSZHQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDAoeWe7lEBXNpFva1qVjzDy3JZfQ"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbPsOMm5BoDXW9njO2Jz18yq"
    portfolio-type:
      - type: "scratch"
      
  - image : "https://i.ytimg.com/vi/-iVkE5BjZ7o/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDVXdc4RJEQCEUMSflfs4iKR04s1g"
    url: "https://www.youtube.com/playlist?list=PLVdkFG00DhbMGiGPOKnkPKLXAj8bXkTmf"
    portfolio-type:
      - type: "mblock"

  - image : "https://arduinoturkbatu.github.io/tulyacss/assets/img/logo.png"
    url: "https://arduinoturkbatu.github.io/tulyacss"
    portfolio-type:
      - type: "web"


#-------------------------------
# Exprerience Section

experience-title: Zaman Çizelgesi
experience:
- {name: Arduino, icon: 'icon-1.png', date: '2018 - Şimdi', organization: ''}
- {name: App Invertor, icon: 'icon-2.png', date: '2020 - Şimdi', organization: ''}
- {name: HTML5 , icon: 'icon-3.png', date: '2021 - Şimdi', organization: ''}
    


#-------------------------------
# Contact Section

contact-title: İletişim
contact-email: batuakyar07@gmail.com
